(unit-smiley (normal)
    (file "./data/smiley32.png"))
(unit-troll (normal)
    (file "./data/trollface32.png"))

(tile-floor (normal grayscale)
    (solid-colour 100 200 100))
(tile-wall (normal grayscale)
    (solid-colour 50 20 20))

(zone-fog (normal)
    (solid-colour 0 0 0 128))
(zone-move (normal)
    (solid-colour 0 255 0 128))
(zone-move-outer (normal)
    (solid-colour 0 128 0 128))
(zone-attack (normal)
    (solid-colour 255 0 0 128))

(grid-thin (normal)
    (file "./data/hexthingrid2.png"))
