(pc
    (sprite-name . unit-smiley)
    (name . "Player Character")
    (max-hp . 84)
    (speed . 200)
    (native-layer . 0)
    (melee-attack . (0 8 4))
    (defense . (0 0 0)))
(troll
    (sprite-name . unit-troll)
    (name . "Player Character")
    (max-hp . 43)
    (speed . 500)
    (native-layer . 0)
    (melee-attack . (0 8 4))
    (defense . (0 0 0)))
