(scout
    (sprite-name . unit-troll)
    (name . "Scout")
    (max-hp . 80)
    (speed . 400)
    (native-layer . 0)
    (melee-attack . (0 8 3))
    (defense . (0 0 0)))
(swordsman
    (sprite-name . unit-rage)
    (name . "Swordsman")
    (max-hp . 100)
    (speed . 300)
    (native-layer . 0)
    (melee-attack . (10 8 5))
    (defense . (0 0 0)))
(shieldmaiden
    (sprite-name . unit-smiley)
    (name . "Shieldmaiden")
    (max-hp . 100)
    (speed . 300)
    (native-layer . 0)
    (melee-attack . (0 8 4))
    (defense . (10 0 250)))
